### ISSUE TITLE
Feature request: add lines filtering while sorting

### ISSUE THREAD

**Issue by deathmorlock** [davidmoten/big-sorter#1]
Hello! Thanks for your work!
Can you add simple feature for text files sorting  - add ability to set 2 optional filters for lines by the MIN and MAX length.
I mean  just filter lines from the source so that they are ignored by the sorting and never appear in the final result. 

I asked about it because for 100 gb file it tooks me about 24h to sort it , and about 3 days to delete lines by length with linux  sort, sed tools.
With your project i can sort 100gb in 2 hours and that will be awesome to filtering lines "on the fly"

**Comment by davidmoten** [comment]
Your welcome, hopefully we can get your use case working nicely. 

The key for you is that you can specify the input as an InputStream rather than just a file. That then gives you the ability to transform an InputStream to another InputStream that is filtered on the fly.

Below is some code that will do what you want. You'll need to add the dependency [com.github.davidmoten:io-extras:0.1.3](https://search.maven.org/artifact/com.github.davidmoten/io-extras/0.1.3/jar) (which I deployed to Maven Central today).

```java
File inputFile = ...;
Stream<byte[]> stream = 
  new BufferedReader(new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8))
    .lines()
    .filter(line -> line.length() >= MIN_LENGTH && line.length <= MAX_LENGTH)
    .map(line -> (line + "\n").getBytes(StandardCharsets.UTF_8));
InputStream in = IOUtil.toInputStream(stream);
```

**Comment by davidmoten** [comment]
I'm also having a think about how to make it a bit easier as a library feature.

**Comment by davidmoten** [comment]
ok, easier now. I'll release soon.
```java
Sorter
  .linesUtf8()
  .input(in)
  .output(out)
  .filter(line -> line.length() >=MIN_LENGTH && line.length() <= MAX_LENGTH) 
  .sort();
```

**Comment by davidmoten** [comment]
I've adjusted it again so that the transforms (filter, map, etc) happen just after the `input()` method in the builder. Makes more sense. Released to Maven Central as 0.1.12:

```java
Sorter
  .linesUtf8()
  .input(in)
  .filter(line -> line.length() >=MIN_LENGTH && line.length() <= MAX_LENGTH) 
  .output(out)
  .sort();
```

**Comment by deathmorlock** [comment]
Awesome work! 
Just tested. Sorted and filtered 92 GB text file in 2 hours !!
If you want to make filter feature more advanced -> add support of RegExp.

**Comment by davidmoten** [comment]
>If you want to make filter feature more advanced -> add support of RegExp. \

There's nothing stopping you using a regex in the filter:

```java
Pattern pattern = Pattern.compile("\\d+");

Sorter
  .linesUtf8()
  .input(in)
  .filter(line -> pattern.matcher(line).matches()) 
  .output(out)
  .sort();
```

**Comment by davidmoten** [comment]
closing, if you want to talk regex I can reopen.
