### ISSUE TITLE
sorting List

### ISSUE THREAD

**Issue by D063520** [davidmoten/big-sorter#27]
Hi,

thank you for providing this library!

This is not really an issue but more a question ...

I wanted to know if there is a way to use this library to sort an ArrayList? The library would then take care of writing the necessary data to disk ...

Thank you

**Comment by davidmoten** [comment]
Not directly. What is in the ArrayList? If you already have it in memory just apply Collections.sort. You might use a more general form of List that wasn't all in memory all the time as input to Sorter but you'd have to write an InputStream around that list. If that's what you want I can help but you'll need to describe the use case with detail.

**Comment by D063520** [comment]
Yes, you are right ... not well formulated .... probably what I was searching is a List implementation that supports disked based sorting ..... basically all methods like a List but with disked based sorting. Do you have this internally maybe?

**Comment by D063520** [comment]
Or in general ... lets say I have elements of a certain class "myClass" with a comparator "myComparator" and I want to sort these .... how would one pass the myClass instances to the library?

**Comment by davidmoten** [comment]
So Sorter is designed to sort arbitrary objects as long as they have a Serialized form for writing to disk so yes an arbitrary List can be sorted but you need to specify how it gets serialized and deserialized. What object types are you sorting? What else do you need to know?

**Comment by davidmoten** [comment]
As long as you provide a serialize method and deserialize method i could provide an input method to pass an Iterable or Stream. Would that do?

**Comment by D063520** [comment]
I think it is super clear to you but somehow not to me ....

Let's say the class is:

class Pair {
 Long valueY;
Long positionY;
@Override public String toString() { return String.format("%d %d", valueY,positionY); }
};

with comparator

(Pair o1, Pair o2) -> {
  if (o1.valueY.equals(o2.valueY)) {
     return o1.positionY.compareTo(o2.positionY)	
}

How to I pass multiple Pair objects to the sorter? 

Yes an iterator would do I think!

**Comment by davidmoten** [comment]
Oh and there already exist methods to return the sort result as a stream. See README.md.

**Comment by D063520** [comment]
Did not thought about the output part to much (I saw you can stream out which is really nice) .... my problem now is rather how to ingest the data  ......

**Comment by davidmoten** [comment]
Because disk is used you need to think about how to serialize that object
to disk. You might use a comma delimited line with two long values for
instance. You might instead serialize those two long values to 16 bytes
(binary form). So you have a serialization method in mind for your class?

**Comment by D063520** [comment]
Hi,

two long separated by comma will do! In fact for me it is not so important how it is represented on disk ....

Salut
D063520

**Comment by davidmoten** [comment]
Ok, no problem. I'll provide the new input methods tomorrow.

**Comment by D063520** [comment]
cool, thank you very much!

**Comment by davidmoten** [comment]
Can you review PR #28 please.

**Comment by davidmoten** [comment]
oops, forgot to make a release. It's on Maven Central 0.1.18.
