### ISSUE TITLE
Feature request: unique functions

### ISSUE THREAD

**Issue by deathmorlock** [davidmoten/big-sorter#3]
1. Ability while sorting -> delete duplicates
2. Ability to compare 2 files and save different entries to file
3. Ability to compare 2 files and save same entries  to file
4.Ability to compare 2 files and delete duplicates from 1st file in 2nd ( VERY USEFUL FUNC !)

In other word clone functions of Unix uniq command. Why i ask about it ? Cuz in Unix this command works VERY slow and in single thread and it useless versus huge files. At same time it requeres that files should be sorted before - so this feature are in concept of big-sorter.

**Comment by davidmoten** [comment]
1. Looks easy to offer that option and a reasonable inclusion in this library
2, 3, 4. Presumably one would sort the two files then run through them save same, different, complement. Looks easy to do, could make an example.

**Comment by deathmorlock** [comment]
Great!  write usage example and i will test all func on huge files!
Thanks!

**Comment by davidmoten** [comment]
That one is done and merged to master.

**Comment by davidmoten** [comment]
Opened #5 with your other requirements, closing this as done
