### ISSUE TITLE
Feature request: All files from folder as  input

### ISSUE THREAD

**Issue by deathmorlock** [davidmoten/big-sorter#4]
Ability to set as input  - folder and all files in it will be also very useful. Thanks!

Usage example:
We have folder with 100 text files from 1 to 200 gb.  Lines in files can duplicate. Also not all Lines match our conditions. 
We using  all features:
```
. input(folder)
. filter(...).
.uniq(remove duplicates) 
.output(result)
.split(10gb) 
```

Awaiting result:  we have sorted files 10 gb each,  with uniq Lines across all files and Lines are compliant  to our conditions.

AMAZING!

**Comment by davidmoten** [comment]
Multiple files as input should be no problem. What I'd suggest is that I support specifying a collection or array of files to the `input` method and you can build that collection/array as you like (from `folder.listFiles()` for example).

**Comment by deathmorlock** [comment]
Yep, it will be nice!

**Comment by davidmoten** [comment]
Righto I've added unit tested support for multiple input files/InputStreams to master. You can now do:

```java
.input(folder.listFiles())
.filter(...).
.unique() 
.output(result)
```

**Comment by davidmoten** [comment]
closing as done (not released to Maven Central yet)
