### ISSUE TITLE
Support move (final step) between different physical devices

### ISSUE THREAD

**Issue by epragtbeamtree** [davidmoten/big-sorter#41]
Hi @davidmoten ,

Just wanted to thank you for creating this library. I've used it for a small project to sort an unsorted 20 GB file, and your library was a life saver, and thank you for maintaining this!

(Btw, I did encounter a small issue: I had to run my application on Windows, with a D: and C: drive. The data was on the D: drive, and the merged and split file was created on c:\temp (or similar). When the file was eventually merged, the file couldn't be moved from C:\ to D:\, it seems NIO doesn't like moving files over drives. I worked around it by setting the temp dir to d:\ too, that fixed it)

Cheers,
Erik

**Comment by davidmoten** [comment]
Glad it was useful @epragtbeamtree!

Re your NIO move issue might be good to fallback to a copy + delete action if the move action fails. I'll have a look at it.

**Comment by epragtbeamtree** [comment]
Cheers, and my apologies for not providing a proper stack trace. I found an older screenshot, I'm not sure if it helps:

<img width="1842" alt="image" src="https://user-images.githubusercontent.com/91307175/155910925-08fb36c6-0604-4304-b7e4-d59f00b5ec1c.png">

**Comment by davidmoten** [comment]
I think all we need to do is drop the ATOMIC_MOVE option. Can you do a little test with this java code on Windows please?
```java
public class Main {

    public static void main(String[] args) throws IOException {
        Files.move(new File("D:\\temp.txt").toPath(), new File("C:\\temp.txt").toPath(), StandardCopyOption.REPLACE_EXISTING);
    }
    
}
```
Change the filenames as you like of course.

**Comment by epragtbeamtree** [comment]
@davidmoten I'm unfortunately on a Mac, it's that I ran into this issue in "production", which is running Windows. I've asked my colleagues, but Java + Windows + Multiple Partitions is a rare combination so far.

**Comment by davidmoten** [comment]
Got multiple physical disks on your Mac? If so ATOMIC_MOVE should fail for that too I think. Unfortunately my linux laptop has only one physical disk so can't test it there.

**Comment by epragtbeamtree** [comment]
I'm afraid not. It's just a MacBook Pro. What I could potentially do is connect a USB disk, would that reproduce it?

**Comment by davidmoten** [comment]
Yep should do I reckon.

Run the code below to see if it fails (adjust filenames) and then remove ATOMIC_MOVE option and see if it passes:

```java
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

public class Main {

    public static void main(String[] args) throws IOException {
        Files.move(new File("a").toPath(), new File("b").toPath(), StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
    }
    
}
```

**Comment by epragtbeamtree** [comment]
I ran the code (or actually a variation of it), and while the `ATOMIC_MOVE` fails, the `REPLACE_EXISTING` version works over different file systems.

**Comment by epragtbeamtree** [comment]
`
        Files.move(
                new File("/Volumes/My Passport/Test/test1.txt").toPath(),
//                new File("/Volumes/My Passport/Test/test2.txt").toPath(),
                new File("/tmp/test5.txt").toPath(),
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.ATOMIC_MOVE);

`

The above code fails. With only the `REPLACE_EXISTING`, it works.

**Comment by epragtbeamtree** [comment]
```java
    public static void main(String[] args) throws IOException {
        Files.move(
                new File("/Volumes/My Passport/Test/test1.txt").toPath(),
                new File("/tmp/test6.txt").toPath(),
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.ATOMIC_MOVE);
    }
```

Results in:

```
Exception in thread "main" java.nio.file.AtomicMoveNotSupportedException: /Volumes/My Passport/Test/test1.txt -> /tmp/test6.txt: Cross-device link
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:415)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at test.Main.main(Main.java:11)
```

**Comment by davidmoten** [comment]
Beaut, does it pass if you remove ATOMIC_MOVE?

**Comment by epragtbeamtree** [comment]
Yep, that works fine.

**Comment by davidmoten** [comment]
oh I see you already answered that, thanks. Great, I'll merge the PR and build a new release.

**Comment by davidmoten** [comment]
Release 0.1.19 is on Maven Central now with the fix. Will be available for download there in about 10 minutes and will be indexed for searches sometime tomorrow.

**Comment by epragtbeamtree** [comment]
Awesome @davidmoten ! Appreciate it! I'll update my code to use the latest!

**Comment by epragtbeamtree** [comment]
(and PS: I really just wanted to thank you, this bug report was mostly an afterthought, since I already had a workaround. Do appreciate fixing it!)

**Comment by davidmoten** [comment]
no worries, will help someone else later so thanks for the report.
