### ISSUE TITLE
Sort big file of integers

### ISSUE THREAD

**Issue by sfairas** [davidmoten/big-sorter#44]
I was having a play with your big-sorter library on github and I really like how efficient it is to sort big files without consuming too much memory.

At the moment I am trying to sort a really big file with integers in it where each integer is in a new line. Something like this:

```
450675107
1882573565
66904383
1151654340
1805777826
1605337641
505724756
1956321588
1606345524
179429565
```

I tried using the following code:
```java
Sorter
      .linesUtf8()
      .input(inputFileWithIntegers.toFile())
      .filter(line -> !line.isEmpty())
      .map(line -> Integer.valueOf(line.toLowerCase()))
      .output(sortedFile)
      .maxFilesPerMerge(100) // default is 100
      .maxItemsPerFile(100000) // default is 100,000
      .initialSortInParallel() // may want to use a large maxItemsPerFile for this to be effective
      .bufferSize(8192) // default is 8192
      .sort();
```
But it complains in "map" where I'm trying to convert the strings into Integers. Without a "map" it sorts the string representation of the integer and that results an output that is not correctly sorted.

I would really appreciate it if you could let me know how I can map the strings to integers and correctly sort this file.

Many thanks

**Comment by davidmoten** [comment]
This will do the job:

```java
Sorter //
          .serializerLinesUtf8() //
          .comparator((a, b) -> Integer.compare(Integer.parseInt(a), Integer.parseInt(b))) //
          .input(new File("src/test/resources/numbers.txt")) //
          .filter(line -> !line.isEmpty()) //
          .output(new File("target/numbers-sorted.txt")) //
          .sort();
```
However, throughout the process (intermediate files) the format remains as string lines and there would be significant overhead in the Integer.parseInt and toString calls.

I've released 0.1.20 which enables a more efficient method discussed in https://github.com/davidmoten/big-sorter#example-for-sorting-integers-from-a-text-file.

As you've pointed out `Util.convert` method was not public in 0.1.20 so I'll fix that shortly and I'd like to see some more convenience methods for this situation in the Sorter builder.

**Comment by davidmoten** [comment]
I've made it easier again to do this more efficient sort. See PR #45 for review (if you like).

**Comment by davidmoten** [comment]
`inputMapper` and `outputMapper` have been added to the Sorter builder via #45 which makes your use case easy to specify and more efficient. See README.md for more details. Those new methods are in 0.1.21 which is on Maven Central now.
