### ISSUE TITLE
Writer needs flushing after using Util-methods to get complete results

### ISSUE THREAD

**Issue by bjornhilstad** [davidmoten/big-sorter#8]
Played around with Util methods (findSame, findDifferent, findComplement) and I noticed I needed to flush the Writer after calling these to get complete results. Comparing two files where I had just removed two lines from one of them I got nothing for findDifferent and findComplement, and findSame was missing some lines at the end of the files.
After calling flush on the Writer after using the find-methods I got the expected results instead.
Maybe Util-methods should handle the flush for me?

Also, I think the example for the use of Util is not quite up to date with the actual API.

Thanks for the library.

**Comment by davidmoten** [comment]
>Played around with Util methods (findSame, findDifferent, findComplement) and I noticed I needed to flush the Writer after calling these to get complete results.

Don't forget to close a Writer to get the results, that will flush and release resources. Did you close the writer? It's not appropriate for those Util methods to call flush.

I'll check the docs, thanks.

**Comment by davidmoten** [comment]
I checked https://github.com/davidmoten/big-sorter#comparing-sorted-files and I think it's accurate re https://github.com/davidmoten/big-sorter/blob/5f378651f4c24f833e4db499abf1be3bf72cd730/src/main/java/com/github/davidmoten/bigsorter/Util.java#L79-L80.

Which part of the docs did you think was wrong?

**Comment by bjornhilstad** [comment]
I was using version 0.1.14 because that was shown by github as latest
release. But I now see that you also have 0.1.15 where the File based
variants are added.
So that explains why I thought the doc was off.

The flushing issue was just my fault. Thanks.

tor. 22. okt. 2020 kl. 01:00 skrev Dave Moten <notifications@github.com>:

**Comment by davidmoten** [comment]
Ah, my bad, I forgot to publish the release on github as well for 0.1.15. 

BTW 0.1.16 is on Maven Central today (and I updated the github releases page).
